smoothing and clamping
inkstitch/inkstitch pull request #1803
Opened 2022-08-26 03:15 UTC by lexelby

Under the hood, this adds two new cool library functions:
* `smooth_path()` -- smooth a potentially jagged path, rounding corners, with specified smoothness (like Inkscape's "Simplify")
* `clamp_path_to_polygon()` -- given a path, prevent it from straying outside a polygon.

I've showcased these features by adding a new option to Contour Fill, "Smoothness".  It smooths the stitch path and then ensures it stays within the polygon (because smoothing can cause it to go outside).  Currently only works for Inner to Outer.

Before:

![image](https://user-images.githubusercontent.com/4446653/186809952-032f5454-724a-4819-ade3-43f23eaf0546.png)

After (smoothness 10):

![image](https://user-images.githubusercontent.com/4446653/186810079-c779c658-ba09-4a2f-99b6-2e1fc5e3987c.png)

2022-08-26 03:17 UTC, lexelby commented
Currently smoothing can cause the end of the stitching to be cut off, which is not ideal.  Maybe that's fine, though.

2022-11-16 07:11 UTC, kaalleen requested changes
I just tested this shortly. With a smoothness value of 10 it always really goes wild on my end, so I had to use much, much smaller values.

2022-11-16 07:11 UTC, kaalleen commented on lib/utils/clamp_path.py
> +    if len(border_pieces) == 3:
better use border_pieces.geoms since shapely says it's deprecated to use it like that directly.

2022-11-16 07:11 UTC, kaalleen commented on lib/utils/clamp_path.py
> +        return [border_pieces[1],
same thing here and in the following line (border_pieces.geoms[1], etc.)

2023-01-18 02:46 UTC, lexelby commented
This should really be called "smoothing and clamping and meander fill" now :D

This is still very much a work in progress.  I mostly pushed so that I didn't lose my code if my laptop caught fire.  Feel free to test out the meander fill, though.  I think most of the tiles need to be shrunk a bit so that the default size works for normal-sized fill shapes, so try a meander scale of 20%.

2023-01-18 02:53 UTC, lexelby commented
If anyone wants to hack on this and push commits, be my guest!

2023-02-06 04:11 UTC, lexelby commented
To do:

* get rid of the "buffer_size" concept in Tile
  * it's redundant with the a negative "Expand" setting in fill
  * remove the circles from each tile SVG
* expose Expand setting in meander fill
* switch to using max stitch length instead of running stitch length to dictate the meander running stitch length
* prune and fix the tiles:
  * remove ones that don't work well
  * fix any tiles where the nodes don't match up between repeats
  * remove redundant ones
* switch to a directory model for tiles like with lettering
  * add `tile.json` and `tile.svg` for each tile
  * tile.json should contain a name
  * make the name translatable like with fonts
  * give them better names?

Future features that are probably best for a later PR, since this one is getting huge:

* thumbnails for tiles
* meander pattern dropdown with tile thumbnails
* rotation and translation for the meander pattern

2023-02-08 19:53 UTC, lexelby commented
I decided to stick with the running_stitch_length param for meander running stitch, because there's already a tolerance parameter to go with it.  I adjusted the docs to make it clear that it's used for meander too.

2023-02-08 19:54 UTC, lexelby commented
Another to do item: rebase on #2006 and use @kaalleen's combo box param support which is nicer than my attempt.

2023-02-08 20:00 UTC, lexelby commented
And another:
* remove dead ends in to_graph() to avoid letting the initial path start or end on one

2023-02-12 03:33 UTC, lexelby commented
Some of the tiles just don't work well.  I'm starting to see something that I think might contribute to that: many lines meeting all at the same point.  8 or 9 seems to be a problem, and even 7 or 6.  I think the reason is that once a path hits that vertex, the algorithm never allows it to use that vertex ever again.  If most of the vertices are like that, then it quickly eliminates almost all vertices and has nowhere to go.

2023-02-19 03:32 UTC, lexelby commented
All of the above to do items are done.  Another thing to add in the future would be a display of the graph in the params simulator.  It'd be so cool if Elements could have a way to give Params extra stuff to be drawn.  Then when the user selects a tile, the graph would show up before the stitch path starts rendering, so they could understand what they were selecting.

2023-02-19 03:33 UTC, lexelby commented
I think this is ready to go!

2023-02-19 10:45 UTC, kaalleen commented on lib/elements/fill_stitch.py
> +import numpy as np
np is never used

2023-02-19 10:48 UTC, kaalleen commented
Works beautifully. Thanks for all the work you've put into this. This is so very nice to have!!

2023-02-22 15:15 UTC, kaalleen approved these changes

2023-02-23 01:22 UTC, lexelby commented
Alright, I'm shipping it. :D This might cause a merge conflict in #2006 because I stole the `combo` param type code from that one.  I think git may be smart enough to see that both branches had the same change and merge it, but we'll see.

2023-02-23 01:22 UTC, merged